
name = "ebonidatin"
compatibility_date = "2024-03-01"
pages_build_output_dir = ".next"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ebonidatin"

[[d1_databases]]
binding = "DB"
database_name = "ebonidatin-db"
database_id = "ebonidatin-db"


[env.production]
variables = { NODE_VERSION = "18", R2_BUCKET_NAME = "ebonidatin" }

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
