name = "ebonidatin"
compatibility_date = "2024-03-01"
pages_build_output_dir = ".next"

[env.production]
variables = { NODE_VERSION = "18" }
{
  "observability": {
    "enabled": false,
    "head_sampling_rate": 1,
    "logs": {
      "enabled": true,
      "head_sampling_rate": 1,
      "persist": true,
      "invocation_logs": true
    },
    "traces": {
      "enabled": true,
      "persist": true,
      "head_sampling_rate": 1
    }
  }
}
